# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'Greenwheels Logistics' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
use_react_native!(
    :hermes_enabled => false
  )

  # Pods for Greenwheels Logistics
   pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens/RNScreens.podspec'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'


  target 'Greenwheels LogisticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end